### ISSUE TITLE
License forbids additional restrictions

### ISSUE THREAD

**Issue by Calinou** [bmbrands/theme_bootstrap#358]
You should remove this part from the README:

> Modify this theme

> Do not modify or clone this theme. 

You can discourage people from doing it, but you cannot legally forbid it.

**Comment by bmbrands** [comment]
That text was added there to discourage people creating a copy of the theme and changing it's code since this code is kept up to date as much as possible and the smart approach is to use it as a parent theme for Moodle. This text is part of the theme description, not the license. 

The theme itself is distributed using a GPL license so legally you can clone / modify and hack all you want.

**Comment by Calinou** [comment]
Thanks for the clarification, this issue can probably be closed now.
