### ISSUE TITLE
Moodle 2.9 dev amd JavaScript broken

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/theme_bootstrap#363]
For some reason the adm JavaScript is not working in Moodle 2.9

**Comment by gjb2048** [comment]
Hi Bas,

In what way not working?  Works for me in Shoelace, Campus and Shoehorn.  In those themes I've done console logging to see the code loading.

Cheers,

Gareth

**Comment by gjb2048** [comment]
P.s.  The AMD patch from me was derived from the working Shoehorn version, so I'm happy that the code works.

**Comment by bmbrands** [comment]
I could not get the modal popup to work I copied from getbootstrap. I can see the console log messages but when I add another console log statement just before the Modal code I don't see it.
I was compiling the amd stuff using Moodle's 2.9 Grunt (very very slow)
So perhaps somewhere it get's stuck. But if it is working in Shoehorn there might be some little thing missing in bootstrap?

**Comment by bmbrands** [comment]
How did you compile the AMD stuff?

**Comment by gjb2048** [comment]
Using the adapted Grunt file supplied in the patch - amd task.  As the core one has a bug on Windows.  There's a tracker for that - I can dig up later.

I can test later if you want me to.

**Comment by gjb2048** [comment]
I'd not tested the Modal, but the carousel, dropdown and accordion are working in Shoehorn, so seemed fine.

**Comment by gjb2048** [comment]
Unless I'd missed the Modal in the AMD port of the code.  Tricky to check on iPod! ;)

**Comment by gjb2048** [comment]
See 'grunt amd' here: https://github.com/gjb2048/theme_bootstrap/blob/master_jamd/Gruntfile.js

**Comment by gjb2048** [comment]
Modal is in the source: https://github.com/gjb2048/theme_bootstrap/blob/master_jamd/amd/src/bootstrap.js

**Comment by gjb2048** [comment]
Humm, Modal or Accordion not working in Shoehorn too, will investigate.

**Comment by gjb2048** [comment]
I sit corrected, Carousel does not work in Shoehorn either :( - but Dropdown does and with logging proven, humm!

**Comment by gjb2048** [comment]
Ok, I have a hunch its because I've combined the files: https://github.com/InvisiLabs/bootstrap-amd/tree/v1.0.1%2Bbootstrap.3.3.4/lib and the 'Plugin' function is redefined several times.  And yet in the original the 'Plugin' is within its own scoped function: https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L1200 - unlike Bootstrap base were the same line is a different name: https://github.com/moodle/moodle/blob/MOODLE_29_STABLE/theme/bootstrapbase/amd/src/bootstrap.js#L998

Need to see if I can have split AMD module files in Moodle!
