### ISSUE TITLE
Cleanup actions for Moodle 2.9

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/theme_bootstrap#364]
For 2.9 I am planning to

Remove bootswatches in less and Grunt. That has all been moved to the Bootswatch theme (except the icon changes)
Remove the zoom feature. That could be a child theme feature too.
Get jquery running
Make sure less is being updated with mdl 2.9.
Have a nicer user dropdown (update renderers)
Fix all issues!!

**Comment by emmarichardson** [comment]
Any idea on when fixes might be done for 2.9?  Such a great theme with so many great themes dependent on it!!!

**Comment by bmbrands** [comment]
I trying to find some time to put into the theme. It's been crazy busy. There is just a few tweaks to make so it should not take more than a week :)

**Comment by BenKelada** [comment]
Hey great work on the theme,
Is there a list of things still open for 2.9? 
It looks like jquery is running with amd modules?
i cant see any yui anywhere still or am i missing something?
if you point some out open issues I can potentially contribute the fixes, cheers,
Ben

**Comment by bmbrands** [comment]
Hi Ben,

Thanks! Wow I just ready my post saying finishing the theme should not take more than a week, *shame*. It looks like these are the open issues

**Comment by BenKelada** [comment]
Hey Bas,
we are doing a new project, with a new theme, we had it based off bootstrapbase, and the cleanm theme (mustache template based clean theme)
We switched to inherit this theme_bootstrap theme and are in the process of adjusting our mustache templates with the BS3 classes, looking straight forward so far, the JS works as expected, if we find issues ill raise them here and try put the fixes up as well.
Cheers!

**Comment by BenKelada** [comment]
has any discussion been had on moving to renderers + mustache templates?

**Comment by bmbrands** [comment]
I still not convinced using Mustache instead of php in your template make development better or easier. I think the implementation of Mustache in Moodle is not the way Mustache is intended to be used. The amount of Mustache templates in Moodle core is very little and I would not be surprised if it will be dropped again in future releases. But who knows. For now I won't be putting any effort in adding it into this theme.

**Comment by gjb2048** [comment]
I have looked into this as well for my themes and at the moment it is a lot of effort for no recognised gain.  It would be a good learning exercise in a simple theme.  It appears to move things towards MVC as they are in J2EE with JSP etc. which technically in terms of architectural design is good, but there is a long way to go yet.  Whilst the existing method is supported, effort for me is in other more important areas.

**Comment by emmarichardson** [comment]
Martin seemed pretty excited about the Mustache implementation at Mountain Moot so not sure that it will go away but who knows…guess if no-one jumps on the bandwagon, it might just fade out.

So back to the time frame…??  Upgrading next week - just wondering if I need to use Gareth’s hacks to fix stuff or if Bootstrap will be ready..?

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037<https://ecboces.zoom.us/my/emmar>




On July 29, 2015 at 1:37:19 AM, Gareth J Barnard (notifications@github.com<mailto:notifications@github.com>) wrote:

I have looked into this as well for my themes and at the moment it is a lot of effort for no recognised gain. It would be a good learning exercise in a simple theme. It appears to move things towards MVC as they are in J2EE with JSP etc. which technically in terms of architectural design is good, but there is a long way to go yet. Whilst the existing method is supported, effort for me is in other more important areas.

**Comment by bmbrands** [comment]
Hi Emma,

There aren't a lot of open issues left so it shouldn't take too long. I just need to find some spare time to work on this project and with the new school year starting soon I don't have much of that :) I don't want to make promises at this point but I'll try to free up some time.

I don't know what hacks made by Gareth your are referring to. Would be interesting to know!

**Comment by emmarichardson** [comment]
Mainly the fix for the Messaging pop up box - that was the main problem I was having.  I see that he had mentioned it to you a while back but didn’t see it in your latest version.  I totally understand about the school year - buried with that myself.  Not a coder but happy to help test if that helps at all!

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037<https://ecboces.zoom.us/my/emmar>




On July 29, 2015 at 6:19:43 AM, Bas Brands (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi Emma,

There aren't a lot of open issues left so it shouldn't take too long. I just need to find some spare time to work on this project and with the new school year starting soon I don't have much of that :) I don't want to make promises at this point but I'll try to free up some time.

I don't know what hacks made by Gareth your are referring to. Would be interesting to know!

**Comment by gjb2048** [comment]
Hi Bas,

Just this port of styles from core:
https://github.com/gjb2048/moodle-theme_shoehorn/commit/8db9134d09ce7562970e198c383e6247d7f26690
.

G


[image: --]
Gareth J Barnard
[image: http://]about.me/gjbarnard
<http://about.me/gjbarnard>

**Comment by bmbrands** [comment]
Ah yes Gareth, That's already been merged into the bootstrap theme :) @emmarichardson all help is more than welcome especially help on testing! So if you find any issue, however small, reporting it here move this theme forward :)

**Comment by emmarichardson** [comment]
Which branch is it in?  I downloaded master from your git about a week ago but didn’t see it…

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037<https://ecboces.zoom.us/my/emmar>




On July 29, 2015 at 6:30:51 AM, Bas Brands (notifications@github.com<mailto:notifications@github.com>) wrote:

Ah yes Gareth, That's already been merged into the bootstrap theme :) @emmarichardson<https://github.com/emmarichardson> all help is more than welcome especially help on testing! So if you find any issue, however small, reporting it here move this theme forward :)

**Comment by gjb2048** [comment]
I believe with Essential / Shoehorn etc. I've just been following the GitHub commits on the bootstrapbase LESS files and selectively implementing what Mary has been up to and MDL-50869 - but that's a BS2.3.2 issue only.

**Comment by bmbrands** [comment]
@emmarichardson it's all in the master branch. The message stuff is here: https://github.com/bmbrands/theme_bootstrap/blob/master/less/moodle/message.less#L330-L377

**Comment by emmarichardson** [comment]
Oh thanks.  I will have to try it again.  I wonder if Elegance is overriding it.  Will check again.

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037<https://ecboces.zoom.us/my/emmar>




On July 29, 2015 at 6:41:57 AM, Bas Brands (notifications@github.com<mailto:notifications@github.com>) wrote:

@emmarichardson<https://github.com/emmarichardson> it's all in the master branch. The message stuff is here: https://github.com/bmbrands/theme_bootstrap/blob/master/less/moodle/message.less#L330-L377

**Comment by BenKelada** [comment]
I really dont think mustache templates are going anywhere :)
The whole element library stuff is based off it, 
We are implementing a mix of urs' mustache based clean theme, and this bootstrap theme
https://moodle.org/mod/forum/discuss.php?d=311119 / https://github.com/uhunkler/moodle/commits/MOODLE_29_mustaches 

the templates are making things a lot easier for front end dev, e.g. bumping from bs2->bs3 meant changing a bunch of classes inside the templates which was really easy.

A benefit is it is much easier for themers to override the html/dom and classes in the dom by overriding the mustache templates rather than having to override the renderer and deal with the icky php/html output
